name: Feature Request
description: Schlage eine neue Funktion oder Verbesserung vor.
title: "[Feature] "
labels: 'enhancement'
body:
  - type: textarea
    id: summary
    attributes:
      label: Kurzbeschreibung
      description: Fasse das Feature in 1-3 Sätzen zusammen.
      placeholder: Kurze, prägnante Zusammenfassung der Idee
    validations:
      required: true

  - type: checkboxes
    id: already-exists
    attributes:
      label: Hast du nachgeschaut, ob es schon ein Issue/Pull Request für dieses Feature gibt?
      description: Falls es bereits ein passendes Issue/Pull Request gibt, beteilige dich bitte dort anstatt ein neues zu erstellen.
      options:
        - label: Ja, ich habe gesucht und kein passendes Issue/Pull Request gefunden.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Motivation
      description: Welches Problem soll gelöst werden? Warum ist das wichtig?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Vorgeschlagene Lösung
      description: Beschreibe, wie das Feature idealerweise funktionieren sollte. Gern stichpunktartig.
      value: |
        - ...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Nutzen/Impact
      description: Welchen Mehrwert bringt das Feature und für wen?
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories (optional)
      description: Formuliere gern als "Als [Rolle] möchte ich [Funktion], damit [Nutzen]".
      value: |
        - Als ...
        - Als ...
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Akzeptanzkriterien
      description: Was muss erfüllt sein, damit das Feature als fertig gilt?
      value: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
      description: Welche alternativen Lösungen hast du in Betracht gezogen?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      description: Wie dringend ist die Umsetzung?
      options:
        - Niedrig
        - Mittel
        - Hoch
        - Kritisch
    validations:
      required: false

  - type: input
    id: related
    attributes:
      label: Verwandte Issues/PRs
      description: Verlinke ggf. verwandte Issues oder Pull Requests.
      placeholder: "z. B. #123, #456"
    validations:
      required: false

  - type: textarea
    id: designs
    attributes:
      label: Mockups/Skizzen (optional)
      description: Füge Bilder/Skizzen hinzu, um die Idee zu verdeutlichen.
      placeholder: Klicke auf das Feld und nutze die Option "Paste, drop or click to add files".
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technische Hinweise
      description: Hinweise zur Implementierung, Risiken, Migrationsplan etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Mitwirkung
      description: Bietest du Unterstützung bei der Umsetzung an?
      options:
        - label: Ich kann bei der Umsetzung mithelfen (Code).
        - label: Ich kann bei Konzeption/Design/Tests unterstützen.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Wähle einen prägnanten Titel, der dieses Feature gut beschreibt!